# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: OLED add-on
version: "0.0.17"
slug: oled
description: Use OLED screens via i2c
url: "https://github.com/mhwlng/ha-addons/tree/main/oled"
stage: experimental
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
services: 
  - mqtt:need
init: false
apparmor: false
full_access: true
devices:
  - /dev/i2c-0
  - /dev/i2c-1
  - /dev/i2c-10
  - /dev/i2c-22
map:
  - config:rw
options:
  message: "Hello world!"
  display_interface_serial: i2c
  display_interface_port: 1
  display_interface_address: 60
  display_type: sh1106
  display_rotate: "0"
  display_width: 128
  display_height: 64
  font_height: 16
  font_name: FreePixel
schema: 
  message: str
  display_interface_serial: list(i2c)
  display_interface_port: int
  display_interface_address: int
  display_type: list(ssd1306|ssd1309|ssd1322|ssd1325|ssd1327|ssd1331|ssd1351|ssd1362|sh1106|sh1107|ws0010)
  display_rotate: list(0|1|2|3)
  display_width: int
  display_height: int
  font_height: int
  font_name: list(FreePixel|FreeSans|SF-Compact|DejaVuSans|DejaVuSansMono||DejaVuSans-Bold|pixelmix|miscfs_|fontawesome-webfont|Volter__28Goldfish_29|ProggyTiny)
#image: "ghcr.io/home-assistant/{arch}-addon-example"
